[package]
name = "agb-core"
version = "0.1.0"
authors = ["Atlas <achille@heraud.xyz>"]

[features]

[dependencies]
time = "0.1.38"

[dev-dependencies]
image = "0.10.4"
serde = "1.0.75"
serde_json = "1.0.26"
serde_derive = "1.0.75"
