[package]
name = "agb-web"
version = "0.1.0"
authors = ["Achille Heraud <achille@heraud.xyz>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.0.2"
wasm-bindgen = "0.2.15"
agb-core = {path = ".."}
